apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue_cra
  labels:
    app: vue_cra
spec:
  selector:
    matchLabels:
      app: vue_cra
  template:
    metadata:
      labels:
        app: vue_cra
    spec:
      containers:
        - name: vue_cra
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_40ca647d755d