apiVersion: v1
kind: Service
metadata:
  labels:
    app: vue_cra
  name: vue_cra
spec:
  ports:
    - name: 3000-3000
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: vue_cra
  type: LoadBalancer